import { describe, expect, it } from "vitest";
import * as core from "../src/index.js";

describe("public api surface", () => {
  it("exports all required modules", () => {
    const expected = [
      "VERSION",
      "NODE_TYPES",
      "LINK_TYPES",
      "SpecFrontmatterSchema",
      "DecisionFrontmatterSchema",
      "SessionFrontmatterSchema",
      "LinkSchema",
      "ProvenanceSchema",
      "VerificationSchema",
      "FrontmatterSchemaByNodeType",
      "parseFrontmatter",
      "serializeFrontmatter",
      "parseId",
      "formatSequentialId",
      "nextSequentialId",
      "formatSessionId",
      "VAULT_DIR",
      "vaultPath",
      "configPath",
      "indexPath",
      "archivePath",
      "ConfigSchema",
      "defaultConfig",
      "loadProjectConfig",
      "mergeConfig",
      "folderForNodeType",
      "nodeTypeForFolder",
      "vaultExists",
      "readNode",
      "writeNode",
      "listNodeIds",
      "listNodeFiles",
      "loadTemplate",
      "renderTemplate",
      "normalizeFrontmatter",
      "normalizeTags",
      "runValidation",
      "computeBacklinks",
      "archiveIfNeeded",
      "archiveAllStaleStatuses",
      "isArchivable",
      "globalDir",
      "sharedDir",
      "listProjects",
      "registerProject",
      "unregisterProject",
      "touchProject",
      "applyCairndexBlock",
      "CAIRNDEX_BLOCK_START",
      "CAIRNDEX_BLOCK_END",
      "sha256",
      "runSync",
      "writeSyncBaseline",
      "readSyncBaseline",
      "generateAutoSession",
      "createWatcher",
      "applyAutoFixes",
      "assertContained",
    ];
    for (const name of expected) {
      expect(core, `missing export: ${name}`).toHaveProperty(name);
    }
  });
});
